//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaphysicsIndustries.Ligra {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetaphysicsIndustries.Ligra.HelpStrings", typeof(HelpStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absolute value function
        ///  abs(x)
        ///  
        ///Returns the absolute value of x, x for (x &gt;= 0) and -x for (x &lt; 0)..
        /// </summary>
        internal static string abs {
            get {
                return ResourceManager.GetString("abs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arccosine function
        ///  acos(x)
        ///  
        ///Returns the arccosine of x. That is, if cos(y) = x, then acos(x) = y..
        /// </summary>
        internal static string acos {
            get {
                return ResourceManager.GetString("acos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arccotangent function
        ///  acot(x)
        ///  
        ///Returns the arccotangent of x. That is, if cot(y) = x, then acot(x) = y..
        /// </summary>
        internal static string acot {
            get {
                return ResourceManager.GetString("acot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arccosecant function
        ///  acsc(x)
        ///  
        ///Returns the arccosecant of x. That is, if csc(y) = x, then acsc(x) = y..
        /// </summary>
        internal static string acsc {
            get {
                return ResourceManager.GetString("acsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arcsecant function
        ///  asec(x)
        ///  
        ///Returns the arcsecant of x. That is, if sec(y) = x, then asec(x) = y..
        /// </summary>
        internal static string asec {
            get {
                return ResourceManager.GetString("asec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arcsine function
        ///  asin(x)
        ///  
        ///Returns the arcsine of x. That is, if sin(y) = x, then asin(x) = y..
        /// </summary>
        internal static string asin {
            get {
                return ResourceManager.GetString("asin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arctangent function
        ///  atan(x)
        ///  
        ///Returns the arctangent of x. That is, if tan(y) = x, then atan(x) = y..
        /// </summary>
        internal static string atan {
            get {
                return ResourceManager.GetString("atan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The atan2 function
        ///  atan(y, x)
        ///  
        ///Returns the arctangent of y/x..
        /// </summary>
        internal static string atan2 {
            get {
                return ResourceManager.GetString("atan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ceiling function
        ///  ceil(x)
        ///  
        ///Returns the lowest integer that is greater than or equal to x..
        /// </summary>
        internal static string ceil {
            get {
                return ResourceManager.GetString("ceil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string commands {
            get {
                return ResourceManager.GetString("commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cosine function
        ///  cos(x)
        ///  
        ///Returns the cosine of x..
        /// </summary>
        internal static string cos {
            get {
                return ResourceManager.GetString("cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cotangent function
        ///  cot(x)
        ///  
        ///Returns the cotangent of x, which is equal to 1 / tan(x)..
        /// </summary>
        internal static string cot {
            get {
                return ResourceManager.GetString("cot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cosecant function
        ///  csc(x)
        ///  
        ///Returns the cosecant of x, which is equal to 1 / sin(x)..
        /// </summary>
        internal static string csc {
            get {
                return ResourceManager.GetString("csc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The derive operator
        ///  derive(f(x), x)
        ///  
        ///Returns the derivative of f(x) with respect to x..
        /// </summary>
        internal static string derive {
            get {
                return ResourceManager.GetString("derive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The floor function
        ///  floor(x)
        ///  
        ///Returns the highest integer that is less than or equal to x..
        /// </summary>
        internal static string floor {
            get {
                return ResourceManager.GetString("floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string functions {
            get {
                return ResourceManager.GetString("functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligra - Advanced Mathematics Visualization and Simulation Program
        ///
        ///General Help: 
        ///  help &lt;topic&gt; 
        /// 
        ///Available Topics: 
        ///  Ligra 
        ///   
        ///  Functions: cos, sin, tan, sec, csc, cot, acos,   
        ///             asin, atan, atan2, asec, acsc, acot,   
        ///             ln, log, log2, log10, sqrt,  
        ///             int, abs, rand, ceil, u 
        ///
        ///  Operators: + - * / 
        ///   
        ///  Special: derive 
        ///   
        ///  Plotting: plot, plot3d;
        ///  
        ///  Commands: help, clear, vars, delete, history, example.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ligra {
            get {
                return ResourceManager.GetString("ligra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The natural logarithm function.
        /// </summary>
        internal static string ln {
            get {
                return ResourceManager.GetString("ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string log10 {
            get {
                return ResourceManager.GetString("log10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string log2 {
            get {
                return ResourceManager.GetString("log2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string operators {
            get {
                return ResourceManager.GetString("operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve Plot
        ///  plot(x, f1(x), f2(x), ... fn(x))
        ///  
        ///  x - independent variable that defines the &quot;x axis&quot;
        ///  fn(x) - the expressions to plot
        ///
        ///  Plots one or more curves..
        /// </summary>
        internal static string plot {
            get {
                return ResourceManager.GetString("plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Surface Plot
        ///  plot3d(x, y, f(x,y))
        ///  plot3d(x, y, f(x,y), fillColor)
        ///  plot3d(x, y, f(x,y), fillColor, wireColor)
        ///  plot3d(x, y, f(x,y), xMin, xMax, yMin, yMax, zMin, zMax)
        ///  plot3d(x, y, f(x,y), xMin, xMax, yMin, yMax, zMin, zMax, fillColor, wireColor)
        ///  
        ///  x - first independent variable
        ///  y - second independent variable
        ///  f(x,y) - the expression to plot
        ///  fillColor - the color of the surface of the plot; default is green
        ///  wireColor - the color of the wireframe of the plot; default is black [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plot3d {
            get {
                return ResourceManager.GetString("plot3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string plotting {
            get {
                return ResourceManager.GetString("plotting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string rand {
            get {
                return ResourceManager.GetString("rand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string sec {
            get {
                return ResourceManager.GetString("sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sine function
        ///  sin(x)
        ///  
        ///Returns the sine of x..
        /// </summary>
        internal static string sin {
            get {
                return ResourceManager.GetString("sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbolic calculus.
        /// </summary>
        internal static string special {
            get {
                return ResourceManager.GetString("special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square root.
        /// </summary>
        internal static string sqrt {
            get {
                return ResourceManager.GetString("sqrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default time variable.
        /// </summary>
        internal static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string tan {
            get {
                return ResourceManager.GetString("tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit step function.
        /// </summary>
        internal static string u {
            get {
                return ResourceManager.GetString("u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string variables {
            get {
                return ResourceManager.GetString("variables", resourceCulture);
            }
        }
    }
}
